version: '2'
services:
  web:
    build: .
    volumes:
      - "./app:/src/app"
    ports:
      - "3030:3000"
    links:
      - "db:mongo"
    environment:
      - "TEST=${TEST}"
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "dbdata:/data/db"
volumes:
  dbdata:
    driver: local